[profile.default]
libs = ["lib", "dependencies"]
remappings = [
  "@openzeppelin-contracts-5.5.0/=dependencies/@openzeppelin-contracts-5.5.0/",
  "@openzeppelin-contracts-upgradeable-5.5.0/=dependencies/@openzeppelin-contracts-upgradeable-5.5.0/",
  "forge-std-1.11.0/=dependencies/forge-std-1.11.0/",
  "openzeppelin-foundry-upgrades-0.4.0/=dependencies/openzeppelin-foundry-upgrades-0.4.0/",
]
solc = "^0.8"

[dependencies]
forge-std = "1.11.0"
"@openzeppelin-contracts-upgradeable" = "5.5.0"
openzeppelin-foundry-upgrades = "0.4.0"
"@openzeppelin-contracts" = "5.5.0"

[soldeer]
remappings_regenerate = true
remappings_location = "config"
